import Head from 'next/head'

import B from '../components/background'

export default function Home() {
  return (
    <B className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        Hello world!
      </main>

      <footer className="">
      </footer>
    </B>
  )
}
