import Head from 'next/head'

import B from '../components/background'

type PropsChildren = {
  name: string
}

export default function Home({children}: PropsChildren) {
  return (
    <B>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {children}
      </main>

      <footer className="">
      </footer>
    </B>
  )
}
