import Head from "next/head"
import { useRouter } from 'next/router'
import Link from "next/link"
import { ReactNode, useState } from "react"
import NavBar from "./navbar"

type PropsChildren = {
    children: ReactNode
}

export default function Layout({ children }: PropsChildren) {
    const [checkRouter, setCheckRouter] = useState(useRouter().pathname == "/");
    
    return (
        <div className="h-screen w-full font-pontserrat">
            <Head>
                <title>dcdevs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <NavBar />
            
            <main className="w-full h-full pt-16 sm:pt-24">
                <div className={`px-4 py-7 sm:p-y sm:pr-0 sm:w-4/5 h-full mx-auto overflow-y-auto relative ${checkRouter ? "" : "md:border-l-2 border-dotted border-black-25"}`}>
                    {children}
                    <div className={`hidden sm:block ${checkRouter ? "sm:absolute sm:bottom-4 sm:right-2 lg:absolute lg:bottom-10 lg:left-0" : "sm:absolute sm:bottom-4 sm:right-2 lg:fixed lg:top-1/2 lg:bottom-1/2 lg:right-[91%]"}`}>
                        <ul className={`flex gap-3 ${checkRouter ? "sm:flex-row" : "sm:flex-row lg:flex-col"} items-center`}>
                            <li>
                                <Link href="https://github.com/dc7devs" target="__blank">
                                    <img className="hover:fill-black" src="/icons/Github.svg" alt="Github" />
                                </Link>
                            </li>

                            <li>
                                <Link href="https://www.linkedin.com/in/diego-c-silva-487b171a5/" target="__blank">
                                    <img className="hover:fill-black" src="/icons/Linkedin.svg" alt="Linkedin" />
                                </Link>
                            </li>

                            <li>
                                <Link href="https://www.youtube.com/channel/UCQCBtV_fonx-JZj-OnIFcSw" target="__blank">
                                    <img className="hover:fill-black" src="/icons/Youtube.svg" alt="Youtube" />
                                </Link>
                            </li>

                            <li>
                                <Link href="https://discord.com/users/687863744541491294" target="__blank">
                                    <img className="hover:fill-black" src="/icons/Discord.svg" alt="Discord" />
                                </Link>
                            </li>

                            <li>
                                <Link href="mailto:diegocaetano444@outlook.com" target="__blank">
                                    <img className="hover:fill-black" src="/icons/email.svg" alt="E-mail" />
                                </Link>
                            </li>
                        </ul>
                    </div>
                </div>
            </main>
        </div>
    )
}