import Head from "next/head"
import { useRouter } from 'next/router'
import Link from "next/link"
import { ReactNode, useState } from "react"
import { SquaresFour, X } from "phosphor-react"
import Modal from "./modal"

type PropsChildren = {
    children: ReactNode
}

export default function Layout({ children }: PropsChildren) {
    const router = useRouter();

    const [checkRouter, setCheckRouter] = useState(router.pathname == "/");
    const [isOpenedModal, setIsOpenedModal] = useState(false);

    function changeCurrentStateModal() {
        setIsOpenedModal(!isOpenedModal);
    }
    
    return (
        <div className="h-screen w-full font-pontserrat">
            <Head>
                <title>{router.pathname.slice(1).toLowerCase()} - Diego Silva</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <nav className="h-12 w-full text-base text-zinc-800/70 flex justify-between items-center px-8 border-b border-dashed border-black/50 md:px-0 md:justify-around md:border-0 md:h-16 absolute top-0">
                <Link href="/">
                    <div className="w-10 h-10 md:w-12 md:h-12 rounded-full ring-2 ring-violet-700/25 shadow-lg shadow-violet-700/25 bakcdrop-blur relative">
                        <img className="object-cove rounded-full" src="/images/My.png" alt="Althor image" />
                    </div>
                </Link>

                <div className="flex justify-center items-center">
                    <ul className="hidden sm:flex justify-stretch items-cente gap-x-3">
                        <li className={`${router.pathname == "/" ?  "text-zinc-800/90 font-semibold" : "text-base" } font-medium sm:min-w-max sm:w-16 sm:flex sm:justify-center sm:hover:text-violet-900/80 sm:hover:medium transition duration-75 ease-in-out md:text-lg md:w-20 `}>
                            <Link href="/">Home</Link>
                        </li>
                        <li className={`${router.pathname == "/about" ?  "text-zinc-800/90 font-semibold" : "text-base"} font-medium sm:min-w-max sm:w-16 sm:flex sm:justify-center sm:hover:text-violet-900/80 sm:hover:medium transition duration-75 ease-in-out md:text-lg md:w-20`}>
                            <Link href="/about">About</Link>
                        </li>
                        <li className={`${router.pathname == "/contact" ?  "text-zinc-800/90 font-semibold" : "text-base"} font-medium sm:min-w-max sm:w-16 sm:flex sm:justify-center sm:hover:text-violet-900/80 sm:hover:medium transition duration-75 ease-in-out md:text-lg md:w-20`}>
                            <Link href="/contact">Contact</Link>
                        </li>
                        <li className={`${router.pathname == "/projects" ?  "text-zinc-800/90 font-semibold" : "text-base"} font-medium sm:min-w-max sm:w-16 sm:flex sm:justify-center sm:hover:text-violet-900/80 sm:hover:medium transition duration-75 ease-in-out md:text-lg md:w-20`}>
                            <Link href="/projects">Projects</Link>
                        </li>
                    </ul>

                    <hr className="hidden sm:block w-px h-4 bg-separator/80 mx-5 shadow-md md:mx-7" />

                    <button
                        onClick={() => changeCurrentStateModal()}
                        className="relative z-50 text-3xl hover:text-violet-900/80 transition duration-75 ease-in-out"
                    >
                        {isOpenedModal ? <X size={32} /> : <SquaresFour />}
                    </button>
                </div>

                {isOpenedModal && <Modal />}
            </nav>
            
            <main className="w-full h-full pt-16 sm:pt-24">
                <div className={`px-4 py-7 sm:p-y sm:pr-0 sm:w-4/5 h-full mx-auto overflow-y-auto relative ${checkRouter ? "" : "md:border-l-2 border-dotted border-black/25"}`}>
                    {children}
                    <div className={`hidden sm:block ${checkRouter ? "sm:absolute sm:bottom-4 sm:right-2 lg:absolute lg:bottom-10 lg:left-0" : "sm:absolute sm:bottom-4 sm:right-2 lg:fixed lg:top-1/2 lg:bottom-1/2 lg:right-[91%]"}`}>
                        <ul className={`flex gap-3 md:gap-4 ${checkRouter ? "sm:flex-row" : "sm:flex-row lg:flex-col"} items-center`}>
                            <li className="hover:text-zinc">
                                <Link href="https://github.com/dc7devs" target="__blank">
                                    <img src="/icons/Github.svg" alt="Github" />
                                </Link>
                            </li>

                            <li className="hover:text-zinc">
                                <Link href="https://www.linkedin.com/in/diego-c-silva-487b171a5/" target="__blank">
                                    <img src="/icons/Linkedin.svg" alt="Linkedin" />
                                </Link>
                            </li>

                            <li className="hover:text-zinc">
                                <Link href="https://www.youtube.com/channel/UCQCBtV_fonx-JZj-OnIFcSw" target="__blank">
                                    <img src="/icons/Youtube.svg" alt="Youtube" />
                                </Link>
                            </li>

                            <li className="hover:text-zinc">
                                <Link href="https://discord.com/users/687863744541491294" target="__blank">
                                    <img src="/icons/Discord.svg" alt="Discord" />
                                </Link>
                            </li>

                            <li className="hover:text-zinc">
                                <Link href="mailto:diegocaetano444@outlook.com" target="__blank">
                                    <img src="/icons/email.svg" alt="E-mail" />
                                </Link>
                            </li>
                        </ul>
                    </div>
                </div>
            </main>
        </div>
    )
}