name: "[CD] vercel preview deployment"

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
      branches:
        - dev
jobs:
    call-sync-main:
        name: Call sync-main-branch.yml
        uses: dc7devs/dcdev.me/.github/workflows/sync-main-branch.yml@dev
        if: startsWith(github.event.head_commit.message, 'chore(release)')
    
    # call-release:
    #     name: Call release.yml
    #     uses: dc7devs/dcdev.me/.github/workflows/release.yml@main
    #     secrets: inherit
    #     needs: call-sync-main
    
    call-lint:
        name: Call lint.yml
        uses: dc7devs/dcdev.me/.github/workflows/lint.yml@main

    preview:
        name: Deploy to preview
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20.13.x
      
            - name: Install PNPM
              run: npm i -g pnpm

            - name: Install vercel CLI
              run: |
                pnpm install
                pnpm i --global vercel@latest

            - name: Pull vercel environment information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy project artifacts to vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}