name: Linting
on: workflow_call

jobs:
  lint:
    name: Check Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.x

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run ESLint
        run: pnpm lint