name: 'Sync develop branch'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rebase-to-dev:
    name: Rebase to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Fetch Main
        run: git fetch origin main:main
      - name: Rebase to develop
        run: git rebase main && git push